name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-fmt:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust nightly
      run: rustup install nightly

    - name: Install rustfmt for nightly
      run: rustup component add --toolchain nightly-x86_64-unknown-linux-gnu rustfmt

    - name: Run rustfmt
      run: cargo +nightly fmt -- --check

  cargo-clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run Clippy
      run: cargo clippy --all --all-targets --all-features --no-deps -- --deny warnings

  build:
    runs-on: ubuntu-latest
    needs: [cargo-fmt, cargo-clippy]

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: cargo build --verbose

  test:
    runs-on: ubuntu-latest
    needs: [cargo-fmt, cargo-clippy]

    steps:
    - uses: actions/checkout@v4

    - name: Test
      run: cargo test --workspace -- --nocapture
